/*
 * Copyright 2017-$YEAR original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package example.bootstrap;

import example.MoonPhase;
import io.micronaut.json.JsonMapper;
import io.micronaut.jsonschema.JsonSchema;
import example.schema.JsonSchemaGeneratorService;
import example.sr.SchemaRegistryClient;
import io.micronaut.context.event.ApplicationEventListener;
import io.micronaut.context.event.StartupEvent;
import io.micronaut.core.annotation.NonNull;
import jakarta.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

/**
 * On startup, load JSON Schema generated by micronaut-json-schema for annotated types,
 * register them to Confluent Schema Registry, and log the Oracle SQL snippet for
 * column-level JSON validation using the generated schema.
 *
 * This example does not execute DDL against Oracle; it only emits the SQL you can paste into migrations.
 */
@Singleton
public class SchemaBootstrap implements ApplicationEventListener<StartupEvent> {

    private static final Logger LOG = LoggerFactory.getLogger(SchemaBootstrap.class);

    private final JsonSchemaGeneratorService generator;
    private final SchemaRegistryClient schemaRegistryClient;
    private final boolean syncEnabled;
    private final JsonMapper jsonMapper;

    public SchemaBootstrap(
        JsonSchemaGeneratorService generator,
        SchemaRegistryClient schemaRegistryClient,
        JsonMapper jsonMapper,
        @io.micronaut.context.annotation.Value("${jsonschema.sync.enabled:true}") boolean syncEnabled
    ) {
        this.generator = generator;
        this.schemaRegistryClient = schemaRegistryClient;
        this.jsonMapper = jsonMapper;
        this.syncEnabled = syncEnabled;
    }

    @Override
    public void onApplicationEvent(StartupEvent event) {
        if (!syncEnabled) {
            LOG.info("JSON Schema sync disabled (jsonschema.sync.enabled=false)");
            return;
        }
        // In a real project you might scan the classpath; for this doc example we list known types explicitly.
        var annotatedTypes = List.of(
            MoonPhase.class
        );
        annotatedTypes.forEach(this::processType);
    }

    private void processType(@NonNull Class<?> type) {
        var ann = type.getAnnotation(JsonSchema.class);
        if (ann == null) {
            return;
        }
        String subject = type.getName();

        // Load and canonicalize the schema generated at compile-time
        String schemaJson = generator.loadCanonicalSchema(type);

        // Idempotency: compare against latest SR version schema (if available)
        try {
            String latest = schemaRegistryClient.getLatest(subject);
            if (latest != null) {
                Map<?, ?> latestPayload = jsonMapper.readValue(latest.getBytes(StandardCharsets.UTF_8), Map.class);
                Object rawSchema = latestPayload.get("schema");
                if (rawSchema instanceof String latestSchemaString) {
                    String latestCanon = canonicalize(latestSchemaString);
                    if (latestCanon.equals(schemaJson)) {
                        LOG.info("Schema for subject '{}' is up-to-date; skipping registration", subject);
                        emitOracleSqlSnippet(type.getSimpleName(), schemaJson);
                        return;
                    }
                }
            }
        } catch (Exception e) {
            LOG.warn("Could not check latest schema for subject '{}': {}", subject, e.toString());
        }

        try {
            // Optional: ensure backward compatibility policy per subject
            schemaRegistryClient.setBackwardCompatibility(subject);
        } catch (Exception e) {
            LOG.warn("Could not set BACKWARD compatibility for subject '{}': {}", subject, e.toString());
        }

        // Register new version
        try {
            String resp = schemaRegistryClient.registerJson(subject, schemaJson);
            LOG.info("Registered JSON Schema for subject '{}': {}", subject, resp);
        } catch (Exception e) {
            LOG.error("Failed to register JSON Schema for subject '{}'", subject, e);
            return;
        }

        emitOracleSqlSnippet(type.getSimpleName(), schemaJson);
    }

    private String canonicalize(String schemaString) {
        try {
            Object tree = jsonMapper.readValue(schemaString.getBytes(StandardCharsets.UTF_8), Object.class);
            return jsonMapper.writeValueAsString(tree);
        } catch (Exception e) {
            // If parsing fails, return the original string to avoid blocking the registration
            LOG.warn("Failed to canonicalize latest schema string: {}", e.toString());
            return schemaString;
        }
    }

    private void emitOracleSqlSnippet(String simpleName, String schemaJson) {
        String qQuoted = "q'~" + schemaJson + "~'";
        LOG.info("Oracle column-level JSON VALIDATE SQL snippet for {}:\n\n" +
            "-- New table example\n" +
            "CREATE TABLE person (\n" +
            "  id NUMBER,\n" +
            "  p_record JSON VALIDATE " + qQuoted + "\n" +
            ");\n\n" +
            "-- Existing table example (safer to pre-check data with JSON_SCHEMA_VALID)\n" +
            "ALTER TABLE person\n" +
            "  MODIFY (p_record JSON VALIDATE " + qQuoted + ");\n");
    }
}
